services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  
  haproxy:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - satu
      - dua
    networks:
      - app-network

  satu:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APPID=1111
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/test
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - postgres
    networks:
      - app-network
    ports:
      - "3001:8080"
    

  dua:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APPID=1111
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/test
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - postgres
    networks:
      - app-network
    ports:
      - "3002:8080"

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
